### ISSUE TITLE
[Question] - Terms and Conditions of Use 2019 update

### ISSUE THREAD

**Issue by GuilhE** [artemgordinskiy/Spotifree#108]
Hi,
Regarding the new terms and conditions which state:
> We’ve updated our User Guidelines, making it clear that all types of ad blockers, bots, and fraudulent streaming activities are not permitted;

Since Spotifree doesn't block, it simply mutes, do we - Spotifree users - need to be concerned about our accounts?
I love Spotifree as much as my playlists 😄

Thanks!

**Comment by ArtemGordinsky** [comment]
Hi!

I'm afraid the new Terms and Conditions do apply to Spotifree, so your account may be blocked if you're using it...

**Comment by ali-bahjati** [comment]
Does it mute only Spotify sound or system sound? Maybe it would be fine if it only mutes system sound.

**Comment by jaywilliams** [comment]
It mutes Spotify itself, and I've found from my experience that if you run it for a while Spotify will detect it and eventually stop playing. You'll have to close and re-open the application. Muting the system _may_ work, but I wouldn't put it past Spotify to monitor that as well.
